@ECHO off
ECHO CREATING SORTING FOLDERS

MKDIR "A:\~` - SORTED\ARCHIVES"
MKDIR "A:\~` - SORTED\GRAPHIC_NOVELS"
MKDIR "A:\~` - SORTED\PHOTOS"
MKDIR "A:\~` - SORTED\STORIES"
MKDIR "A:\~` - SORTED\VIDEO"

ECHO SORTING FOLDERS CREATED

PAUSE

ECHO BEGINNING ARCHIVE SORTING
MOVE "A:\MEGA RAW\*.ZIP" "A:\~` - SORTED\ARCHIVES"
MOVE "A:\MEGA RAW\*.RAR" "A:\~` - SORTED\ARCHIVES"
MOVE "A:\MEGA RAW\*.7z" "A:\~` - SORTED\ARCHIVES"

ECHO ARCHIVE SORTING HAS FINISHED

PAUSE

ECHO BEGINNING VIDEO SORTING
MOVE "A:\MEGA RAW\*.MP4" "A:\~` - SORTED\VIDEO"
MOVE "A:\MEGA RAW\*.AVI" "A:\~` - SORTED\VIDEO"
MOVE "A:\MEGA RAW\*.MOV" "A:\~` - SORTED\VIDEO"
MOVE "A:\MEGA RAW\*.MKV" "A:\~` - SORTED\VIDEO"
MOVE "A:\MEGA RAW\*.MPEG" "A:\~` - SORTED\VIDEO"
MOVE "A:\MEGA RAW\*.WEBM" "A:\~` - SORTED\VIDEO"
ECHO VIDEO SORTING HAS FINISHED

PAUSE

ECHO BEGINNING GRAPHIC NOVEL SORTING
MOVE "A:\MEGA RAW\*.PDF" "A:\~` - SORTED\GRAPHIC_NOVELS"
ECHO GRAPHIC NOVEL SORTING HAS FINISHED

PAUSE

ECHO BEGINNING STORY SORTING
MOVE "A:\MEGA RAW\*.TXT" "A:\~` - SORTED\STORIES"
MOVE "A:\MEGA RAW\*.DOCX" "A:\~` - SORTED\STORIES"
ECHO STORY SORTING HAS FINISHED

PAUSE

ECHO BEGINNING PHOTO SORTING
MOVE "A:\MEGA RAW\*.JPG" "A:\~` - SORTED\PHOTOS"
MOVE "A:\MEGA RAW\*.JPEG" "A:\~` - SORTED\PHOTOS"
MOVE "A:\MEGA RAW\*.BMP" "A:\~` - SORTED\PHOTOS"
MOVE "A:\MEGA RAW\*.PNG" "A:\~` - SORTED\PHOTOS"
MOVE "A:\MEGA RAW\*.GIF" "A:\~` - SORTED\PHOTOS"
ECHO PHOTO SORTING HAS FINISHED

ECHO ALL SORTING OPERATIONS HAVE BEEN ACCOMPLISHED

ECHO on